<li class="title">Partners</li>
<li><a href="/partners#escreen">eScreen</a></li>
<li><a href="/partners#honkamp-kruger-and-co">Honkamp Krueger &amp; Co</a></li>
<li><a href="/partners#hr-testing">HR Testing</a></li>
<li><a href="/partners#job-target">Job Target</a></li>
<li><a href="/partners#peoplestrategy">PeopleStrategy</a></li>
<li><a href="/partners#skillsurvey">SkillSurvey</a></li>
<li><a href="/partners#tazworks">TazWorks</a></li>
<li><a href="/partners#tms">Talent Management Solutions</a></li>