<li class="title">Resources</li>
<li><a href="/resources/legal-and-compliance">Legal and Compliance</a></li>
<!-- <li><a href="/resources/white-papers">White Papers</a></li> -->
<li><a href="/resources/advisories">Advisories</a></li>
<li><a href="/resources/fcra-forms">FCRA Forms</a></li>
<li><a href="/resources/glossary">Glossary</a></li>
<li><a href="/resources/faq">FAQ</a></li>
<li><a href="/resources/events">Events Calendar</a></li>
<li><a href="/resources/presentations">Presentations</a></li>
<li><a href="/resources/webinars">Webinars</a></li>
<li><a href="/files/searches-and-product-library.doc">Searches and Products Catalog [Doc]</a></li>